"""
Deterministic fallback generation for when student requests violate level constraints.

This service ensures that fallback responses are:
1. Generated by code, not by hoping the LLM follows instructions
2. Pedagogically sound (explain restriction + offer help + suggest next steps)
3. Never generic ("I can't help" is replaced with "Here's what I CAN do...")
"""

from typing import Dict, List, Optional
from enum import Enum


class ViolationType(str, Enum):
    """Types of violations that trigger fallbacks."""
    CODE_GENERATION_DENIED = "code_generation_denied"
    CODE_ANALYSIS_DENIED = "code_analysis_denied"
    MULTIPLE_FUNCTIONS_DENIED = "multiple_functions_denied"
    NO_VERBAL_SPEC = "no_verbal_spec"
    SCOPE_TOO_BROAD = "scope_too_broad"
    GENERIC = "generic"


class FallbackService:
    """
    Generates deterministic, pedagogical fallback responses.
    
    Design:
    - No LLM calls (deterministic)
    - Structured template: (a) acknowledge, (b) explain restriction, (c) offer help, (d) suggest steps
    - Level-aware: knows what IS allowed at each level
    """

    # Simplified fallback templates (3-4 sentences, no markdown)
    TEMPLATES = {
        ViolationType.CODE_GENERATION_DENIED: (
            "I understand you'd like me to generate code, but based on your course's current settings, "
            "I cannot provide actual code implementations. This restriction helps you build problem-solving skills "
            "by working through the logic yourself. However, I can explain concepts, discuss algorithmic approaches, "
            "or clarify course materials. Click 'Use Fallback' below to get AI-assisted guidance that works within your course constraints."
        ),
        
        ViolationType.CODE_ANALYSIS_DENIED: (
            "I see you've shared code, but based on your course's current {thread_type} settings, I cannot analyze code directly. "
            "This encourages you to build debugging intuition by articulating problems in your own words. "
            "Instead, try describing what your code is trying to do verbally, and I can discuss the approach conceptually. "
            "Click 'Use Fallback' below for AI-assisted help that works within your course constraints."
        ),
        
        ViolationType.MULTIPLE_FUNCTIONS_DENIED: (
            "I understand you're asking for help with multiple functions, but based on your course's current settings, "
            "I can only provide code for one function at a time. This constraint helps you break down problems into manageable pieces. "
            "Please focus on one specific function and describe its purpose clearly. "
            "Click 'Use Fallback' below to get AI-assisted guidance for your request."
        ),
        
        ViolationType.NO_VERBAL_SPEC: (
            "I'd like to help, but based on your course's current {thread_type} settings, I need you to provide a verbal specification before I can generate code. "
            "Please tell me what the function should do, what inputs it takes, and what output it should produce. "
            "This ensures you're thinking through the requirements before implementation. "
            "Click 'Use Fallback' below for AI-assisted help with your request."
        ),
        
        ViolationType.SCOPE_TOO_BROAD: (
            "I can see you're working on a substantial feature, but based on your course's current settings, I can't scaffold entire applications. "
            "My role is to help you learn by tackling focused, specific problems. "
            "Please break this into smaller pieces and ask about one specific component or function at a time. "
            "Click 'Use Fallback' below for AI-assisted guidance that works within your course constraints."
        ),
        
        ViolationType.GENERIC: (
            "Your request doesn't align with the current course constraints, which ensure you're building the right skills at the right pace. "
            "I can answer conceptual questions, explain course materials, or provide strategic guidance on problem-solving. "
            "Try rephrasing your question to focus on concepts or strategy rather than asking me to build something. "
            "Click 'Use Fallback' below for AI-assisted help that works within your course constraints."
        )
    }

    @staticmethod
    def generate_fallback(
        violation_type: ViolationType,
        thread_type: str,
        level_index: Optional[int] = None,
        student_prompt: str = "",
        violations: Optional[List[Dict]] = None
    ) -> str:
        """
        Generate a concise, plain-text fallback response.
        
        Args:
            violation_type: Type of violation that triggered fallback
            thread_type: 'writing', 'testing', or 'debugging'
            level_index: Current level index (0-7 for writing, 0-5 for testing/debugging)
            student_prompt: Original student request
            violations: Optional list of specific violations from rule check (not used in simplified version)
            
        Returns:
            Plain text fallback response (3-4 sentences) explaining the restriction
        """
        template = FallbackService.TEMPLATES.get(
            violation_type,
            FallbackService.TEMPLATES[ViolationType.GENERIC]
        )
        
        # Format the template with thread type
        return template.format(
            thread_type=thread_type.title()
        )

    @staticmethod
    def infer_violation_type(violations: List[Dict], student_prompt: str) -> ViolationType:
        """
        Infer the most appropriate violation type from the violations list.
        
        Uses heuristics based on violation reasons and prompt content.
        """
        if not violations:
            return ViolationType.GENERIC
        
        # Combine all violation reasons
        reasons_text = " ".join([v.get("reason", "").lower() for v in violations])
        prompt_lower = student_prompt.lower()
        
        # Heuristic rules (order matters: most specific first)
        if "multiple function" in reasons_text or "full application" in reasons_text:
            return ViolationType.MULTIPLE_FUNCTIONS_DENIED
        
        if "verbal spec" in reasons_text or "clear spec" in reasons_text:
            return ViolationType.NO_VERBAL_SPEC
        
        if "code analysis" in reasons_text or "analyze code" in reasons_text:
            return ViolationType.CODE_ANALYSIS_DENIED
        
        if any(keyword in prompt_lower for keyword in ["write", "generate", "create", "implement"]):
            if any(code_word in prompt_lower for code_word in ["function", "class", "code", "program"]):
                return ViolationType.CODE_GENERATION_DENIED
        
        if "scope" in reasons_text or "beyond" in reasons_text:
            return ViolationType.SCOPE_TOO_BROAD
        
        return ViolationType.GENERIC
